@startuml
hide empty members
hide circle

class "Ruta13: Ruta" {
    Estado: activa
    Puntualidad: Atrasada
    Destino: Lluja
}

class "Vehículo1: Vehículo" {
    Capacidad: 100
    Modelo: XM100
    Asientos: 50
    Tipo: Bus
}

class "TarifaPasajero: Tarifa" {
    Costo: 1.30
    TipoTarifa: Bus
}

class "TarifaConductor: Tarifa" {
    Costo: 0.50
    TipoTarifa: Bus
}

class "Parada1: Parada" {
    Nombre: Manuel Llano
    Número: 13
    Corresponencia: Ruta13
}

class "Persona1: Persona" {
    Nombre: Santiago Gómez
    Permiso: Pasajero
    Abono: Tarjeta Trimestral
}

class "Persona2: Persona" {
    Nombre: Juan Toca
    Permiso: Conductor
    Abono: Especial Conductor
}

"Ruta13: Ruta" --> "Vehículo1: Vehículo" : Ocupa
"Ruta13: Ruta" --> "Parada1: Parada" : Se compone
"Vehículo1: Vehículo" --> "Parada1: Parada" : Llega
"Persona1: Persona" --> "Parada1: Parada" : Llega
"Persona1: Persona" --> "TarifaPasajero: Tarifa" : Paga
"Persona2: Persona" --> "TarifaConductor: Tarifa" : Paga
"Vehículo1: Vehículo" --> "Persona1: Persona" : Lleva
"Vehículo1: Vehículo" --> "Persona2: Persona" : Lleva
"Vehículo1: Vehículo" --> "TarifaPasajero: Tarifa" : Tiene
"Persona2: Persona" --> "Vehículo1: Vehículo" : Conduce

@enduml